package com.example.dynamodbtest.comments

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.example.dynamodbtest.config.DynamoDBConfig
import java.time.OffsetDateTime

@DynamoDBTable(tableName = "Comment2")
class Comment2(
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    var id: String,

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byMentionId")
    var mentionId: Int,

    @DynamoDBAttribute
    var name: String,

    @DynamoDBAttribute
    var content: String,

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    var deleted: Boolean,

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "byMentionId")
    @DynamoDBTypeConverted(converter = DynamoDBConfig.OffsetDateTimeConverter::class)
    var createdAt: OffsetDateTime,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDBConfig.OffsetDateTimeConverter::class)
    var deletedAt: OffsetDateTime,
)